name: Reporte Diario Amalgam

on:
  schedule:
    # Ejecutar todos los días a las 03:00 AM hora Colombia
    - cron: "0 8 * * *"
  workflow_dispatch:  # Para correrlo manualmente cuando quieras
jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar reporte
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: node report.js

